server.port=8761
spring.application.name=eureka-server

# Hardcodes the server to your local machine
eureka.instance.hostname=localhost
# Tells the server NOT to act like a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Great for local dev: kicks out dead services immediately
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=90000
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health

logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
